### ISSUE TITLE
headerColorOne and headerColorTwo colors

### ISSUE THREAD

**Issue by Elfengour** [javadr/xebaposter#1]
headerColorOne and headerColorTwo do not properly like in latin version, it is not possible to use a beautiful shaded color  (examole: **headerColorOne=black**, % Background color for the header in the content boxes (left side)
h**eaderColorTwo=lightblue,** % Background color for the header in the content boxes (right side)

**Comment by javadr** [comment]
Dear @Elfengour 
Sorry for such a tardy reply! I hadn't noticed this issue!

The mentioned issue is because of the `XeLaTeX` engine, which is out of my hand. 
See [this QA](https://tex.stackexchange.com/questions/262877/xelatex-doesnt-work-properly-with-tikz-when-pgfpage-with-pgfpagesuselayout-is) and compile it with `PdfLaTeX` and `XeLaTeX`engines and see the outputs.
